const hourly = Date.now(3600000);
declare("InternetGatewayDevice.DeviceInfo.HardwareVersion", {path: hourly, value: hourly});
declare("InternetGatewayDevice.DeviceInfo.SoftwareVersion", {path: hourly, value: hourly});
declare("InternetGatewayDevice.DeviceInfo.UpTime", {value: Date.now(300000)});
declare("InternetGatewayDevice.LANDevice.*.WLANConfiguration.*.SSID", {path: hourly, value: hourly});
declare("InternetGatewayDevice.LANDevice.*.WLANConfiguration.*.Enable", {path: hourly, value: hourly});
declare("InternetGatewayDevice.LANDevice.*.LANEthernetInterfaceConfig.*.Enable", {path: hourly, value: hourly});
declare("InternetGatewayDevice.LANDevice.*.Hosts.HostNumberOfEntries", {value: Date.now(300000)});
declare("InternetGatewayDevice.WANDevice.*.WANConnectionDevice.*.WANIPConnection.*.ExternalIPAddress", {path: hourly, value: Date.now(300000)});
declare("InternetGatewayDevice.WANDevice.*.WANConnectionDevice.*.WANIPConnection.*.MACAddress", {path: hourly, value: hourly});
declare("InternetGatewayDevice.WANDevice.*.WANConnectionDevice.*.WANPPPConnection.*.Username", {path: hourly, value: Date.now(300000)});
declare("InternetGatewayDevice.WANDevice.*.WANConnectionDevice.*.WANPPPConnection.*.ExternalIPAddress", {path: hourly, value: Date.now(300000)});
declare("InternetGatewayDevice.WANDevice.*.WANConnectionDevice.*.WANPPPConnection.*.ConnectionStatus", {path: hourly, value: Date.now(300000)});
// --- WAN: nama/tipe/enable koneksi, VLAN (GponLinkConfig), ServiceList, binding LAN/WiFi ---
declare("InternetGatewayDevice.WANDevice.*.WANConnectionDevice.*.WANIPConnection.*.Name", {path: hourly, value: hourly});
declare("InternetGatewayDevice.WANDevice.*.WANConnectionDevice.*.WANIPConnection.*.Enable", {path: hourly, value: hourly});
declare("InternetGatewayDevice.WANDevice.*.WANConnectionDevice.*.WANIPConnection.*.ConnectionType", {path: hourly, value: hourly});
declare("InternetGatewayDevice.WANDevice.*.WANConnectionDevice.*.WANIPConnection.*.ConnectionStatus", {path: hourly, value: Date.now(300000)});
declare("InternetGatewayDevice.WANDevice.*.WANConnectionDevice.*.WANPPPConnection.*.Name", {path: hourly, value: hourly});
declare("InternetGatewayDevice.WANDevice.*.WANConnectionDevice.*.WANPPPConnection.*.Enable", {path: hourly, value: hourly});
declare("InternetGatewayDevice.WANDevice.*.WANConnectionDevice.*.WANPPPConnection.*.ConnectionType", {path: hourly, value: hourly});
declare("InternetGatewayDevice.WANDevice.*.WANConnectionDevice.*.X_CT-COM_WANGponLinkConfig.Enable", {path: hourly, value: hourly});
declare("InternetGatewayDevice.WANDevice.*.WANConnectionDevice.*.X_CT-COM_WANGponLinkConfig.Mode", {path: hourly, value: hourly});
declare("InternetGatewayDevice.WANDevice.*.WANConnectionDevice.*.X_CT-COM_WANGponLinkConfig.VLANIDMark", {path: hourly, value: hourly});
declare("InternetGatewayDevice.WANDevice.*.WANConnectionDevice.*.X_CT-COM_WANEponLinkConfig.Enable", {path: hourly, value: hourly});
declare("InternetGatewayDevice.WANDevice.*.WANConnectionDevice.*.X_CT-COM_WANEponLinkConfig.Mode", {path: hourly, value: hourly});
declare("InternetGatewayDevice.WANDevice.*.WANConnectionDevice.*.X_CT-COM_WANEponLinkConfig.VLANIDMark", {path: hourly, value: hourly});
declare("InternetGatewayDevice.WANDevice.*.WANConnectionDevice.*.WANIPConnection.*.X_ZTE-COM_VLANID", {path: hourly, value: hourly});
declare("InternetGatewayDevice.WANDevice.*.WANConnectionDevice.*.WANIPConnection.*.X_ZTE-COM_VLANEnable", {path: hourly, value: hourly});
declare("InternetGatewayDevice.WANDevice.*.WANConnectionDevice.*.WANPPPConnection.*.X_ZTE-COM_VLANID", {path: hourly, value: hourly});
declare("InternetGatewayDevice.WANDevice.*.WANConnectionDevice.*.WANPPPConnection.*.X_ZTE-COM_VLANEnable", {path: hourly, value: hourly});
declare("InternetGatewayDevice.WANDevice.*.WANConnectionDevice.*.WANIPConnection.*.X_CT-COM_ServiceList", {path: hourly, value: hourly});
declare("InternetGatewayDevice.WANDevice.*.WANConnectionDevice.*.WANPPPConnection.*.X_CT-COM_ServiceList", {path: hourly, value: hourly});
declare("InternetGatewayDevice.WANDevice.*.WANConnectionDevice.*.WANIPConnection.*.X_ZTE-COM_ServiceList", {path: hourly, value: hourly});
declare("InternetGatewayDevice.WANDevice.*.WANConnectionDevice.*.WANPPPConnection.*.X_ZTE-COM_ServiceList", {path: hourly, value: hourly});
declare("InternetGatewayDevice.WANDevice.*.WANConnectionDevice.*.WANIPConnection.*.X_CT-COM_LanInterface", {path: hourly, value: hourly});
declare("InternetGatewayDevice.WANDevice.*.WANConnectionDevice.*.WANPPPConnection.*.X_CT-COM_LanInterface", {path: hourly, value: hourly});
declare("InternetGatewayDevice.WANDevice.*.WANConnectionDevice.*.WANIPConnection.*.X_ZTE-COM_LanInterface", {path: hourly, value: hourly});
declare("InternetGatewayDevice.WANDevice.*.WANConnectionDevice.*.WANPPPConnection.*.X_ZTE-COM_LanInterface", {path: hourly, value: hourly});
declare("VirtualParameters.RXPower", {value: Date.now(300000)});
declare("VirtualParameters.Temperature", {value: Date.now(300000)});
declare("VirtualParameters.WANIP", {value: Date.now(300000)});
declare("VirtualParameters.IPMgmt", {value: Date.now(300000)});
declare("VirtualParameters.PPPoEUsername", {value: Date.now(300000)});
declare("VirtualParameters.WANMAC", {value: Date.now(300000)});
declare("VirtualParameters.Uptime", {value: Date.now(300000)});
declare("VirtualParameters.ClientCount", {value: Date.now(300000)});
declare("VirtualParameters.PONMode", {value: Date.now(86400000)});
declare("VirtualParameters.Model", {value: Date.now(86400000)});
declare("VirtualParameters.RedamanStatus", {value: Date.now(300000)});
declare("VirtualParameters.SuhuStatus", {value: Date.now(300000)});

// --- Kredensial akun web ONT (fitur Akses ONT dashboard) ---
// ONT yang tak punya param ini mengabaikannya tanpa fault (sudah diuji lintas-merk).
declare("InternetGatewayDevice.DeviceInfo.X_CT-COM_TeleComAccount.Password", {path: hourly, value: hourly});
declare("InternetGatewayDevice.UserInterface.X_ZTE-COM_WebUserInfo.AdminName", {path: hourly, value: hourly});
declare("InternetGatewayDevice.UserInterface.X_ZTE-COM_WebUserInfo.UserName", {path: hourly, value: hourly});
declare("InternetGatewayDevice.X_CT-COM_UserInfo.UserName", {path: hourly, value: hourly});
